name: Backend CI

on:
  push:
    branches: ["main"]
  pull_request:
      branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run tests and collect coverage
        run: |
          coverage run -m pytest backend/tests/test_services.py
      #   coverage xml

      # Start containers
      - name: Start backend and DB containers
        run: |
          docker-compose -f docker-compose.yml up --build -d db backend
          sleep 30

      # Run integration tests
      #- name: Run integration tests and collect coverage
      #  run: |
      #     coverage run -m pytest backend/tests/test_controller.py
      #     coverage xml -o backend/tests/integration_tests_coverage.xml

      - name: Stop containers
        run: docker-compose down

      # Upload coverage to Codecov
      - uses: actions/checkout@main
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          # directory: /home/runner/work/gestao-escolar/gestao-escolar/backend/tests/
          # files: /home/runner/work/gestao-escolar/gestao-escolar/backend/tests/coverage.xml
          directory: /home/runner/work/gestao-escolar/gestao-escolar/
          fail_ci_if_error: false
          verbose: true
